variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.14-dind

stages:
    - build
    - deploy
    - deploy-production

.create-secret: &create-secret |
  if kubectl get secret regcred ; then
      echo "There is a regcred. Deleting it..."
      kubectl delete secret regcred
  fi
  kubectl create secret docker-registry regcred --docker-server=$CI_REGISTRY --docker-username=abstack --docker-password=QLxgVSURsjoeHR9qh8A6 --dry-run=client -o yaml | kubectl apply -f -

# Building abstack
build-abstack-production:
    stage: build
    image: docker:stable
    tags: [abstack]
    only: 
      - master
    script:
        - docker build -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/abstack:$CI_COMMIT_SHORT_SHA --build-arg INSTANCE=abstack .
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
        - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/abstack:$CI_COMMIT_SHORT_SHA
    environment:
      name: abstack-production


build-abstack-develop:
    stage: build
    image: docker:stable
    tags: [abstack]
    only:
      - develop
    script:
        - docker build -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/abstack:$CI_COMMIT_SHORT_SHA --build-arg INSTANCE=abstack --build-arg REACT_APP_SPLITIO_API_KEY="" .
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
        - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/abstack:$CI_COMMIT_SHORT_SHA
    environment:
      name: abstack-develop


# Deploy abstack
# deploy-abstack-develop:
#   stage: deploy
#   image: dtzar/helm-kubectl
#   tags: [abstack]
#   script:
#     - helm repo add abstack https://helm.abstractstack.co.uk && helm repo update
#     - *create-secret
#     - helm upgrade --install --set Image=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/abstack:$CI_COMMIT_SHORT_SHA --set Instance=abstack --set Environment=develop abstack abstack/frontend
#     - helm upgrade --install --set Url=dev.abstack.tech --set Instance=abstack --set Environment=develop ingress-frontend abstack/ingress-frontend
#   environment:
#     name: abstack-develop
#     url: https://dev.abstack.tech
#   only:
#     - develop

deploy-abstack-production:
  stage: deploy-production
  image: dtzar/helm-kubectl
  tags: [abstack]
  script:
    - helm repo add abstack https://helm.abstractstack.co.uk && helm repo update
    - *create-secret
    - helm upgrade --install --set Url=abstractstack.co.uk --set Route=/ --set Image=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/abstack:$CI_COMMIT_SHORT_SHA --set Instance=abstack --set Environment=production abstack abstack/frontend
  environment:
    name: abstack-production
    url: https://abstractstack.co.uk
  when: manual
  only:
    - master